/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanNewRouteImport } from './routes/plan/new'
import { Route as PlanIdRouteImport } from './routes/plan/$id'
import { Route as PlanIdIndexRouteImport } from './routes/plan/$id/index'
import { Route as PlanIdShoppingListRouteImport } from './routes/plan/$id/shopping-list'
import { Route as PlanIdFeedbackRouteImport } from './routes/plan/$id/feedback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanNewRoute = PlanNewRouteImport.update({
  id: '/plan/new',
  path: '/plan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIdRoute = PlanIdRouteImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanIdIndexRoute = PlanIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanIdRoute,
} as any)
const PlanIdShoppingListRoute = PlanIdShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => PlanIdRoute,
} as any)
const PlanIdFeedbackRoute = PlanIdFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => PlanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/plan/$id': typeof PlanIdRouteWithChildren
  '/plan/new': typeof PlanNewRoute
  '/plan/$id/feedback': typeof PlanIdFeedbackRoute
  '/plan/$id/shopping-list': typeof PlanIdShoppingListRoute
  '/plan/$id/': typeof PlanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/plan/new': typeof PlanNewRoute
  '/plan/$id/feedback': typeof PlanIdFeedbackRoute
  '/plan/$id/shopping-list': typeof PlanIdShoppingListRoute
  '/plan/$id': typeof PlanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/onboarding': typeof OnboardingRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/plan/$id': typeof PlanIdRouteWithChildren
  '/plan/new': typeof PlanNewRoute
  '/plan/$id/feedback': typeof PlanIdFeedbackRoute
  '/plan/$id/shopping-list': typeof PlanIdShoppingListRoute
  '/plan/$id/': typeof PlanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/onboarding'
    | '/products'
    | '/settings'
    | '/plan/$id'
    | '/plan/new'
    | '/plan/$id/feedback'
    | '/plan/$id/shopping-list'
    | '/plan/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/onboarding'
    | '/products'
    | '/settings'
    | '/plan/new'
    | '/plan/$id/feedback'
    | '/plan/$id/shopping-list'
    | '/plan/$id'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/onboarding'
    | '/products'
    | '/settings'
    | '/plan/$id'
    | '/plan/new'
    | '/plan/$id/feedback'
    | '/plan/$id/shopping-list'
    | '/plan/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  OnboardingRoute: typeof OnboardingRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  PlanIdRoute: typeof PlanIdRouteWithChildren
  PlanNewRoute: typeof PlanNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/new': {
      id: '/plan/new'
      path: '/plan/new'
      fullPath: '/plan/new'
      preLoaderRoute: typeof PlanNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$id/': {
      id: '/plan/$id/'
      path: '/'
      fullPath: '/plan/$id/'
      preLoaderRoute: typeof PlanIdIndexRouteImport
      parentRoute: typeof PlanIdRoute
    }
    '/plan/$id/shopping-list': {
      id: '/plan/$id/shopping-list'
      path: '/shopping-list'
      fullPath: '/plan/$id/shopping-list'
      preLoaderRoute: typeof PlanIdShoppingListRouteImport
      parentRoute: typeof PlanIdRoute
    }
    '/plan/$id/feedback': {
      id: '/plan/$id/feedback'
      path: '/feedback'
      fullPath: '/plan/$id/feedback'
      preLoaderRoute: typeof PlanIdFeedbackRouteImport
      parentRoute: typeof PlanIdRoute
    }
  }
}

interface PlanIdRouteChildren {
  PlanIdFeedbackRoute: typeof PlanIdFeedbackRoute
  PlanIdShoppingListRoute: typeof PlanIdShoppingListRoute
  PlanIdIndexRoute: typeof PlanIdIndexRoute
}

const PlanIdRouteChildren: PlanIdRouteChildren = {
  PlanIdFeedbackRoute: PlanIdFeedbackRoute,
  PlanIdShoppingListRoute: PlanIdShoppingListRoute,
  PlanIdIndexRoute: PlanIdIndexRoute,
}

const PlanIdRouteWithChildren =
  PlanIdRoute._addFileChildren(PlanIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  OnboardingRoute: OnboardingRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  PlanIdRoute: PlanIdRouteWithChildren,
  PlanNewRoute: PlanNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
